### ISSUE TITLE
Design logo

### ISSUE THREAD

**Issue by Jacob8765** [Jacob8765/simon-sings#7]
It'd be really nice to have a logo.

**Comment by Jacob8765** [comment]
It should probably incorporate the name somehow (Simon Sings), and then maybe something musical, like a music note or a staff.

**Comment by enesanc63** [comment]
Can give it a try

**Comment by syauqiahmd** [comment]
can you more specific about logo ?

**Comment by Jacob8765** [comment]
@syauqiahmd I don't have anything super specific in mind besides what I mentioned earlier. Just make sure the logo won't look squished on the navbar.

**Comment by ggabogarcia** [comment]
Hi, I found this issue and I intend to collaborate, I made this design, due to the shape of the typography use the letter M with which I built a very nice icon, it is an M and in the same way, they are the keys of a piano. I hope you like it :) 
# 
![simon sings](https://user-images.githubusercontent.com/35750428/47124218-617c2300-d242-11e8-8a4b-738b40609430.jpg)
# 
I also made a main page design that accompanies the logo. If you want to implement everything, let me know and I will gladly send you the files.
# 
![page](https://user-images.githubusercontent.com/35750428/47124266-aef89000-d242-11e8-9e51-1f47fb3960e8.jpg)

**Comment by ggabogarcia** [comment]
I must clarify that this is completely free. If you want to use it just tell me and I will send you all the editable files.

**Comment by ggabogarcia** [comment]
Yesterday I sent the link to your email, let me know if everything is ok :)

**Comment by Jacob8765** [comment]
@ggabogarcia I got the email. I'll try to add the logo to the game sometime next week. Feel free to create the readme PR if you want
